# Generated by Django 5.1.4 on 2024-12-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
